<?php

return [
    'blocked_customer_keywords' => [
        'officer', 'front officer', 'back officer', 'assigned officer', 'officer list',
        'service officer', 'service-officer', 'service officer assignment',
        'service-window', 'service window assignment', 'officer-window',
        'officer window assignment', 'internal routing', 'activation request',
        'admin user', 'manager data', 'which officer', 'who is officer',
        'who works', 'assigned to service', 'assigned window', 'officer performance',
        'user report', 'show activation request', 'show internal assignment',
        'hojjetaa', 'ramaddii', 'qondaala', 'መስኮት', 'ኦፊሰር', 'ምደባ', 'ማንቃት',
    ],

    'intents' => [
        'services_list' => [
            'list service', 'list services', 'show service', 'show services',
            'first list service', 'available service', 'available services',
            'what services', 'which services', 'services', 'service list',
            'government service', 'online service', 'what can i apply',
            'tajaajila', 'tajaajiloota', 'tarree tajaajilaa',
            'አገልግሎት', 'አገልግሎቶች', 'ዝርዝር',
        ],
        'service_detail' => [
            'what is this service', 'service about', 'who can apply', 'is this service free',
            'how much is service fee', 'available in my woreda', 'available in my subcity',
            'service fee', 'tajaajila kana', 'ይህ አገልግሎት',
        ],
        'service_criteria' => [
            'criteria', 'requirement', 'requirements', 'required', 'document',
            'documents', 'paper', 'papers', 'needed', 'prepare', 'attachment',
            'attachments', 'supporting document', 'what do i need', 'what file',
            'ulaagaa', 'ragaa', 'dokumantii', 'sanada', 'waraqaa',
            'መስፈርት', 'የሚያስፈልግ', 'ሰነድ', 'ማስረጃ',
        ],
        'apply_steps' => [
            'how to apply', 'apply', 'application', 'submit', 'start',
            'fill form', 'start service', 'where do i apply', 'help me apply',
            'do i need login', 'without login', 'application form', 'select city',
            'select subcity', 'select woreda', 'upload documents', 'after submit',
            'tracking number',
            'iyyachuu', 'galchuu', 'akkamitti', 'tarkaanfii',
            'ማመልከት', 'መጀመር', 'ቅጽ', 'መሙላት',
        ],
        'application_tracking' => [
            'track', 'tracking', 'status', 'application status', 'progress',
            'application number', 'request', 'where is my application',
            'approved', 'completed', 'submitted', 'under review',
            'appointment scheduled',
            'hordoffii', 'haala', 'iyyata', 'adeemsa',
            'መከታተል', 'ክትትል', 'ሁኔታ', 'ማመልከቻ',
        ],
        'appointment' => [
            'appointment', 'schedule', 'appointment date', 'appointment time',
            'time', 'location', 'meeting', 'what should i bring',
            'change appointment', 'actions locked', 'beellama', 'guyyaa', 'saatii', 'bakka',
            'ቀጠሮ', 'ቀን', 'ሰዓት', 'ቦታ',
        ],
        'payment' => [
            'payment', 'fee', 'cost', 'paid', 'unpaid', 'receipt',
            'invoice', 'amount', 'where can i pay', 'download receipt', 'payment pending',
            'kaffaltii', 'gatii', 'nagahee',
            'ክፍያ', 'ዋጋ', 'ተከፍሏል', 'ደረሰኝ',
        ],
        'documents' => [
            'uploaded files', 'submitted documents', 'download document', 'download certificate',
            'final certificate', 'approval document', 'correction document', 'replace file',
            'pdf', 'image upload', 'file type',
        ],
        'rejection_return' => [
            'how can i resubmit', 'resubmit', 'rejected', 'returned', 'correction',
            'reason', 'fix', 'rejected reason', 'returned reason', 'edit application',
            'replace wrong file', 'after resubmission',
            'deebi', 'sirreeffama', 'irra deebi', 'sababa',
            'ውድቅ', 'ተመልሷል', 'ማስተካከያ', 'ምክንያት', 'እንደገና',
        ],
        'auth_help' => [
            'login', 'register', 'account', 'password', 'sign in',
            'create account', 'forgot password', 'activate account', 'cannot login',
            'galmaa', 'seeni', 'መመዝገብ', 'መግባት', 'መለያ', 'የይለፍ ቃል',
        ],
        'profile_account' => [
            'update profile', 'change password', 'change phone', 'change address',
            'change email', 'profile',
        ],
        'officer_queue_report' => [
            'assigned applications', 'shared applications', 'returned applications',
            'appointment queue', 'new applications', 'overdue', 'priority',
            'my daily performance', 'my weekly performance', 'completed count',
            'rejected count', 'sla overdue', 'applications by service',
            'applications by window', 'forwarded to me', 'back review',
            'pending approvals', 'technical review',
        ],
        'manager_report' => [
            'escalated applications', 'manager review queue', 'manager decision',
            'assigned to me', 'officer workload', 'front officer performance',
            'back officer performance', 'bottleneck', 'sla violations',
            'city wide report', 'subcity report', 'woreda report',
            'compare subcities', 'compare woredas',
        ],
        'admin_report' => [
            'show users', 'users by role', 'active users', 'disabled users',
            'users in my city', 'users in my subcity', 'users in my woreda',
            'activation requests', 'pending activation', 'approved activation',
            'rejected activation', 'service report', 'service criteria report',
            'form builder report', 'window report', 'service window report',
            'service officer report', 'officer window report', 'dashboard statistics',
        ],
        'super_admin_report' => [
            'full system summary', 'all users', 'all services', 'all applications',
            'all windows', 'all assignments', 'system usage', 'audit log report',
            'city comparison', 'subcity comparison', 'woreda comparison',
            'payment report', 'appointment report', 'rejection reason analytics',
        ],
        'report_questions' => [
            'report', 'reports', 'summary', 'dashboard', 'statistics', 'count',
            'total', 'analytics', 'performance', 'daily', 'weekly', 'monthly',
            'yearly', 'status report', 'application report', 'officer report',
            'service report', 'payment report', 'appointment report', 'sla report',
            'rejection report', 'completion report', 'workload', 'bottleneck',
            'ሪፖርት', 'ማጠቃለያ', 'ስታቲስቲክስ', 'gabaasa', 'cuunfaa',
        ],
        'greeting' => [
            'hello', 'hi', 'hey', 'good morning', 'good afternoon',
            'good evening', 'akkam', 'nagaa', 'akkam jirtu',
            'ሰላም', 'እንዴት ነዎት', 'ጤና ይስጥልኝ',
        ],
    ],
];
